travis:
  secure:
    BINSTAR_TOKEN: NzleSeQD8OUTei+ngXita2marwBOtrXsoi26gfrddNK5gO6qJ8tYQvQwfCh956Ev4KSVvPv79JqOasyacX0YCIoZ/EesI7RGD8icE5OteLCTmUkTpDYMz5p+xpndVUgX7acrix1PcuRgqV7PMj6ellupYxMClSqIb5/AdJNTLhdfDT6klfqxD7Y2tRaRlVEM8ztedWLwFP06YhrWNLml5H+Uq7M3Bj6Gh81rAuLVp5pJjZmPfmsXCxRGCYWsja02aV7Hx0+eFebKZ9q6qes4I5IvM39bZ/rZgR7XcfoQQBxG2g+qSztV+GLZcMdOJd6H7Oj+HbLO91JtayQsMWBnYr9RWRwCKUlrao4I8pDCyKjniTtsUXj2IEGaMa1CenDpXf4WoM3ZxMedqDC6qX/vR5ybGvmhDYduRzwuR9MdPUyL2pspW70pOh+HJLBZcho4KiYtFXWYqHs2UZ2IloVkdcUkHa1/Dvzk7XxR0gVmHYKrnEUYLhl3sYOeXy9pQLEjtlibG0MDRdPy6Mn0ymHX55zputOnID7Ai3/eYIj3wL3QKUxwlFOdSKIZvVI8S+PFn7EE0rgWbVO5FCjVv2iCwO3l5fGOkhYzCjBu9jGGlJ+JdbC0wxGSbTRrT0Vhmf2OlqvlNNsXOHz1luKQQ7cDcd89hyLzONdStR804xJjSpw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
